
package hm;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author akbar
 */
public class Mess extends javax.swing.JFrame {

    /**
     * Creates new form Mess
     */
    public Mess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        capacity = new javax.swing.JTextField();
        BFT = new javax.swing.JTextField();
        LT = new javax.swing.JTextField();
        INSERT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        messid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        DELETE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        READ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DT = new javax.swing.JTextField();
        usn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                     MESS  INFORMATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 70));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MESS CAPACITY:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BREAKFAST TIMING:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 30));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LUNCH TIMING:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 30));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DINNER TIMING:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        capacity.setBackground(new java.awt.Color(240, 240, 240));
        capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityActionPerformed(evt);
            }
        });
        getContentPane().add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 170, 30));

        BFT.setBackground(new java.awt.Color(240, 240, 240));
        BFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFTActionPerformed(evt);
            }
        });
        getContentPane().add(BFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 170, 30));

        LT.setBackground(new java.awt.Color(240, 240, 240));
        LT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTActionPerformed(evt);
            }
        });
        getContentPane().add(LT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, 30));

        INSERT.setBackground(new java.awt.Color(34, 167, 240));
        INSERT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        INSERT.setText("INSERT");
        INSERT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        getContentPane().add(INSERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 90, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MESS ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 20));

        messid.setBackground(new java.awt.Color(240, 240, 240));
        messid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messidActionPerformed(evt);
            }
        });
        getContentPane().add(messid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 170, 30));

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MESS ID", "CAPACITY", "BREAKFAST TIME", "LUNCH TIME", "DINNER TIME"
            }
        ));
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 480, 230));

        DELETE.setBackground(new java.awt.Color(34, 167, 240));
        DELETE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 100, -1));

        UPDATE.setBackground(new java.awt.Color(34, 167, 240));
        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 100, -1));

        READ.setBackground(new java.awt.Color(34, 167, 240));
        READ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        READ.setText("READ");
        READ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        READ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                READActionPerformed(evt);
            }
        });
        getContentPane().add(READ, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 100, -1));

        jButton1.setBackground(new java.awt.Color(34, 167, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, -1, -1));

        jButton2.setBackground(new java.awt.Color(34, 167, 240));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 80, -1));

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DINNER TIMING:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, 30));

        DT.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(DT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, 30));

        usn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hm/IMG-20181107-WA0019.jpg"))); // NOI18N
        getContentPane().add(usn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LTActionPerformed

    private void capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityActionPerformed
        
    }//GEN-LAST:event_capacityActionPerformed

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
       Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
       int  Mess_Id= 0, Capacity = 0;
       String Breakfast_Time = null, Lunch_Time= null,  Dinner_Time= null;
       String studentusn=null;
       

        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
        Mess_Id= Integer.parseInt(this.messid.getText());
        Capacity = Integer.parseInt(this.capacity.getText());
        Breakfast_Time =this.BFT.getText();
        Lunch_Time = this.LT.getText();
        Dinner_Time =this.DT.getText();
     
        String query="insert into mess(MESS_ID,MESS_CAPACITY,MESS_BREAKFAST_TIMING,MESS_LUNCH_TIMING,MESS_DINNER_TIMINGS) values('"+Mess_Id+"','"+Capacity+"','"+Breakfast_Time+"','"+Lunch_Time+"','"+Dinner_Time+"')";

        try {
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();
            st.executeUpdate(query);
              DefaultTableModel model = (DefaultTableModel) table3.getModel();
            model.addRow(new Object[]{Mess_Id,Capacity,Breakfast_Time,Lunch_Time,Dinner_Time});
            JOptionPane.showMessageDialog(rootPane, "Inserted Successful");
          

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }  
               
        
    
    }//GEN-LAST:event_INSERTActionPerformed

    private void BFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFTActionPerformed

    private void messidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messidActionPerformed

    private void READActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_READActionPerformed
        Connection con;
        Statement st;
        ResultSet rst;
        
        String CONN_STRING;
        String USERNAME;
        String PASSWORD;
        String Password_Field = null;
        String Password_Input = null;
      
        String  Mess_Id1= null, Capacity1 = null;
        String Breakfast_Time1 = null, Lunch_Time1= null,  Dinner_Time1= null;
        String query;
        
        
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USERNAME = "root";
        PASSWORD = "";
        query = "select * from mess";
        try {
            
            con = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            st = con.createStatement();
            rst = st.executeQuery(query);
            while (rst.next()) {                
                Mess_Id1  = rst.getString("MESS_ID");
               Capacity1= rst.getString("MESS_CAPACITY");
                Breakfast_Time1= rst.getString("MESS_BREAKFAST_TIMING");
                 Lunch_Time1 = rst.getString("MESS_LUNCH_TIMING");
               Dinner_Time1 = rst.getString("MESS_DINNER_TIMINGS");
               
               DefaultTableModel model = (DefaultTableModel) table3.getModel();
                model.addRow(new Object[]{Mess_Id1,Capacity1,Breakfast_Time1,Lunch_Time1,Dinner_Time1});
            }
            JOptionPane.showMessageDialog(rootPane, "Successful");
            
       

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR IN THE CODE..." + e);
            System.out.println(e);
        }     
    }//GEN-LAST:event_READActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String action = evt.getActionCommand();
        if(action.equals("CANCEL")){
            Option nm=new Option();
            nm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
       Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
      
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
        String query_1 = "select * from mess";
        String MESS_ID = null, query,MESS_id = this.messid.getText(),set = "false";
        String MESS_CAPACITY = null,Breakfast_TIMING = null, Lunch_TIMING = null, Dinner_TIMING=null;
        try {
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();
                
                query = "delete from mess where MESS_ID = '"+MESS_id+"'";
                st.executeUpdate(query);
                set = "true";
                DefaultTableModel model = (DefaultTableModel) table3.getModel();
                model.setRowCount(0);

                while(true){
                       rst = st.executeQuery("select * from mess");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   MESS_id = rst.getString("MESS_ID");
                                   MESS_CAPACITY = rst.getString("MESS_CAPACITY");
                                   Breakfast_TIMING = rst.getString("MESS_BREAKFAST_TIMING");
                                   Lunch_TIMING = rst.getString("MESS_LUNCH_TIMING");
                                   Dinner_TIMING = rst.getString("MESS_DINNER_TIMINGS");
                                  
                                   DefaultTableModel model1 = (DefaultTableModel) this.table3.getModel();
                                   model1.addRow(new Object[] {MESS_id,MESS_CAPACITY,Breakfast_TIMING,Lunch_TIMING,Dinner_TIMING});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
             JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }

    }//GEN-LAST:event_DELETEActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
        int i=table3.getSelectedRow();
        TableModel model= table3.getModel();
        messid.setText(model.getValueAt(i,0).toString());
        capacity.setText(model.getValueAt(i, 1).toString());
        BFT.setText(model.getValueAt(i, 2).toString());
        LT.setText(model.getValueAt(i, 3).toString());
        DT.setText(model.getValueAt(i, 4).toString());
            
    }//GEN-LAST:event_table3MouseClicked

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
       Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
        String  Mess_Id= null, Capacity = null;
        String Breakfast_Time = null, Lunch_Time= null,  Dinner_Time= null;
  
       

        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
       
       
        Mess_Id = this.messid.getText();
        Capacity= this.capacity.getText();
        Breakfast_Time = this.BFT.getText();
        Lunch_Time = this.LT.getText();
        Dinner_Time = this.DT.getText();
      
        String Mess_id = null;
        String query_1 = "select * from mess";
        String capacity= null,breakfast = null, lunch = null, dinner=null,usn=null;
        //JOptionPane.showMessageDialog(rootPane,"successfully updated!!");

        try {
            
            String query = null,querry_2 = null;
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();

            String set = "false";

             

                query = "update mess set MESS_ID = '"+Mess_Id+"',"
                + "MESS_CAPACITY = '"+Capacity+"',MESS_BREAKFAST_TIMING = '"+Breakfast_Time+"',"
                + "MESS_LUNCH_TIMING = '"+Lunch_Time+"',MESS_DINNER_TIMINGS = '"+Dinner_Time+ "'  where MESS_ID = '"+Mess_Id+"'";
                st.executeUpdate(query);
                DefaultTableModel model = (DefaultTableModel) table3.getModel();
                set = "true";
                model.setRowCount(0);

                while(true){
                       rst = st.executeQuery("select * from mess");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   Mess_Id= rst.getString("MESS_ID");
                                   capacity = rst.getString("MESS_CAPACITY");
                                   breakfast = rst.getString("MESS_BREAKFAST_TIMING");
                                   lunch = rst.getString("MESS_LUNCH_TIMING");
                                   dinner = rst.getString("MESS_DINNER_TIMINGS");
                                   
                                   DefaultTableModel model1 = (DefaultTableModel) this.table3.getModel();
                                   model1.addRow(new Object[] {Mess_Id,capacity,breakfast,lunch,dinner});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Fees hg= new Fees();
       hg.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BFT;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField DT;
    private javax.swing.JButton INSERT;
    private javax.swing.JTextField LT;
    private javax.swing.JButton READ;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField capacity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messid;
    private javax.swing.JTable table3;
    private javax.swing.JLabel usn;
    // End of variables declaration//GEN-END:variables
}
