/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hm;

/**
 *
 * @author akbar
 */
public class Option extends javax.swing.JFrame {

    /**
     * Creates new form Option
     */
    public Option() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Fees = new javax.swing.JButton();
        Student = new javax.swing.JButton();
        Hostel = new javax.swing.JButton();
        Room = new javax.swing.JButton();
        Mess = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel2.setText("                                            MENU");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        Fees.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Fees.setText("FEES INFO");
        Fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeesActionPerformed(evt);
            }
        });
        getContentPane().add(Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 220, 90));

        Student.setBackground(new java.awt.Color(255, 255, 255));
        Student.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Student.setText("STUDENT INFO");
        Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentActionPerformed(evt);
            }
        });
        getContentPane().add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 220, 90));

        Hostel.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Hostel.setText("HOSTEL INFO");
        Hostel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HostelActionPerformed(evt);
            }
        });
        getContentPane().add(Hostel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 220, 90));

        Room.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Room.setText("ROOM INFO");
        Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomActionPerformed(evt);
            }
        });
        getContentPane().add(Room, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 220, 90));

        Mess.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        Mess.setText("MESS INFO");
        Mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessActionPerformed(evt);
            }
        });
        getContentPane().add(Mess, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 220, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hm/abstract-colorful-warm-colors-blurred-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
       Student st=new Student();
       st.setVisible(true);
            dispose();
    }//GEN-LAST:event_StudentActionPerformed

    private void HostelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HostelActionPerformed
       Hostel ht= new Hostel();
       ht.setVisible(true);
            dispose();
    }//GEN-LAST:event_HostelActionPerformed

    private void RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomActionPerformed
        Room rm=new Room();
        rm.setVisible(true);
            dispose();
    }//GEN-LAST:event_RoomActionPerformed

    private void MessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessActionPerformed
      Mess mn= new Mess();
      mn.setVisible(true);
            dispose();
    }//GEN-LAST:event_MessActionPerformed

    private void FeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeesActionPerformed
        Fees fs=new Fees();
        fs.setVisible(true);
            dispose();
    }//GEN-LAST:event_FeesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String action = evt.getActionCommand();
        if(action.equals("CANCEL")){
              Login    nm=new Login();
            nm.setVisible(true);
            dispose();}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fees;
    private javax.swing.JButton Hostel;
    private javax.swing.JButton Mess;
    private javax.swing.JButton Room;
    private javax.swing.JButton Student;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
