
package hm;
import java.awt.HeadlessException;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author akbar
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        room = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        beds = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        INSERT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        UPDATE = new javax.swing.JButton();
        READ = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                      ROOM   INFORMATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 70));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROOM ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAPACITY:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME OF STUDENT'S:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 30));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STATUS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, -1));

        room.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 30));

        capacity.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 180, 30));

        beds.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(beds, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 180, 30));

        status.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 30));

        INSERT.setBackground(new java.awt.Color(34, 167, 240));
        INSERT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        INSERT.setText("INSERT");
        INSERT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        getContentPane().add(INSERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 90, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HOSTEL ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 100, -1));

        id.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, 30));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOM ID", "CAPACITY", "NAME", "STATUS", "HOSTEL ID"
            }
        ));
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table4);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 450, 240));

        UPDATE.setBackground(new java.awt.Color(34, 167, 240));
        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 90, -1));

        READ.setBackground(new java.awt.Color(34, 167, 240));
        READ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        READ.setText("READ");
        READ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        READ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                READActionPerformed(evt);
            }
        });
        getContentPane().add(READ, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 90, -1));

        DELETE.setBackground(new java.awt.Color(34, 167, 240));
        DELETE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 90, -1));

        jButton1.setBackground(new java.awt.Color(34, 167, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, -1, -1));

        jButton2.setBackground(new java.awt.Color(34, 167, 240));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hm/IMG-20181107-WA0019.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        Connection con;
        Statement st;
        ResultSet rst;
        
        String CONN_STRING;
        String USERNAME;
        String PASSWORD;
        int Room_Id = 0, Capacity = 0,Hostel_id=0 ;
        String Status = null;
        String Name_of_student = null;
        String Password_Field = null;
        String Password_Input = null;
        String query = null;
        
        Room_Id = Integer.parseInt(this.room.getText());
        Capacity = Integer.parseInt(this.capacity.getText());
        Name_of_student = this.beds.getText();
        Status=this.status.getText();
        Hostel_id = Integer.parseInt(this.id.getText());
         id.setText(Hostel.id.getText());
        
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USERNAME = "root";
        PASSWORD = "";
        query = "insert into ROOM(ROOM_ID,CAPACITY,NAME_OF_STUDENTS,ROOM_STATUS,HOSTEL_ID) values('"+Room_Id+"','"+Capacity+"','"+Name_of_student+"','"+Status+"','"+Hostel_id+"')";
        try {
       
            con = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            st = con.createStatement();
            st.executeUpdate(query);
              DefaultTableModel model = (DefaultTableModel) table4.getModel();
            model.addRow(new Object[]{Room_Id,Capacity,Name_of_student,Status,Hostel_id});
               
            JOptionPane.showMessageDialog(rootPane, "Successful");
             
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR IN THE CODE..." + e);
            System.out.println(e);
        }
          
        
        

    }//GEN-LAST:event_INSERTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String action = evt.getActionCommand();
        if(action.equals("CANCEL")){
            Option nm=new Option();
            nm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
      Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
      
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
        String query_1 = "select * from room";
        String ROOM_Id = null, query,Room_id = this.room.getText(),set = "false";
        String CAPACITY = null,name_of_student = null, status = null, hostel_id=null;
        try {
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();
                
                query = "delete from room where ROOM_ID = '"+Room_id+"'";
                st.executeUpdate(query);
                set = "true";
                DefaultTableModel model = (DefaultTableModel) table4.getModel();
                model.setRowCount(0);

                while(true){
                       rst = st.executeQuery("select * from room");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   Room_id = rst.getString("ROOM_ID");
                                   CAPACITY = rst.getString("CAPACITY");
                                   name_of_student = rst.getString("NAME_OF_STUDENTS");
                                   status = rst.getString("ROOM_STATUS");
                                   hostel_id = rst.getString("HOSTEL_ID");
                                   DefaultTableModel model1 = (DefaultTableModel) this.table4.getModel();
                                   model1.addRow(new Object[] {Room_id,CAPACITY,name_of_student,status,hostel_id});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
             JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }

    }//GEN-LAST:event_DELETEActionPerformed

    private void READActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_READActionPerformed
         Connection con;
        Statement st;
        ResultSet rst;
        
        String CONN_STRING;
        String USERNAME;
        String PASSWORD;
        String Password_Field = null;
        String Password_Input = null;
       
        String Room_Id1= null, Capacity1= null,Hostel_id1=null ;
        String Status1 = null;
        String Name_of_student1 = null; 
        String query;     
        
        
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USERNAME = "root";
        PASSWORD = "";
        query = "select * from room";
        try {
            
            con = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            st = con.createStatement();
            rst = st.executeQuery(query);
            while (rst.next()) {                
                Room_Id1  = rst.getString("ROOM_ID");
               Capacity1= rst.getString("CAPACITY");
                Hostel_id1= rst.getString("HOSTEL_ID");
               Status1 = rst.getString("ROOM_STATUS");
               Name_of_student1 = rst.getString("NAME_OF_STUDENTS");
               DefaultTableModel model = (DefaultTableModel) table4.getModel();
                model.addRow(new Object[]{Room_Id1,Capacity1,Name_of_student1,Status1,Hostel_id1});
            }
            JOptionPane.showMessageDialog(rootPane, "Successful");
            
       

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR IN THE CODE..." + e);
            System.out.println(e);
        }

    }//GEN-LAST:event_READActionPerformed

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
       int i=table4.getSelectedRow();
        TableModel model= table4.getModel();
        room.setText(model.getValueAt(i,0).toString());
        capacity.setText(model.getValueAt(i, 1).toString());
        beds.setText(model.getValueAt(i, 2).toString());
        status.setText(model.getValueAt(i, 3).toString());
        id.setText(model.getValueAt(i, 4).toString());

    }//GEN-LAST:event_table4MouseClicked

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
       Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
        String  Room_id= null, Capacity = null;
        String Status = null, Beds= null,  Id= null;
       
       

        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
       
       
        Room_id = this.room.getText();
        Capacity= this.capacity.getText();
        Status = this.beds.getText();
        Beds = this.status.getText();
        Id = this.id.getText();
        String Room_Id = null;
        String query_1 = "select * from mess";
        String capacity= null,STATUS = null, BEDS = null, ID=null;


        try {
            
            String query = null,querry_2 = null;
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();

            String set = "false";

             

                query = "update room set ROOM_ID = '"+Room_id+"',"
                + "CAPACITY = '"+Capacity+"',NAME_OF_STUDENTS = '"+Status+"',"
                + "ROOM_STATUS = '"+Beds+"',HOSTEL_ID = '"+Id+ "'  where ROOM_ID = '"+Room_id+"'";
                st.executeUpdate(query);
                DefaultTableModel model = (DefaultTableModel) table4.getModel();
                set = "true";
                model.setRowCount(0);
        JOptionPane.showMessageDialog(rootPane,"successfully updated!!");
                while(true){
                       rst = st.executeQuery("select * from room");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   Room_id= rst.getString("ROOM_ID");
                                   capacity = rst.getString("CAPACITY");
                                   STATUS= rst.getString("NAME_OF_STUDENTS");
                                   BEDS= rst.getString("ROOM_STATUS");
                                   ID = rst.getString("HOSTEL_ID");
                                   DefaultTableModel model1 = (DefaultTableModel) this.table4.getModel();
                                   model1.addRow(new Object[] {Room_id,capacity,STATUS,BEDS,ID});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }

    }//GEN-LAST:event_UPDATEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Student hg= new Student();
       hg.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JButton INSERT;
    private javax.swing.JButton READ;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField beds;
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField room;
    private javax.swing.JTextField status;
    private javax.swing.JTable table4;
    // End of variables declaration//GEN-END:variables
}
