
package hm;

import java.awt.HeadlessException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.logging.Level;
import static java.util.logging.Level.SEVERE;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author akbar
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        USN = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        FNAME = new javax.swing.JTextField();
        DEPT = new javax.swing.JTextField();
        ADD = new javax.swing.JTextField();
        PHN = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        HOSTELID = new javax.swing.JTextField();
        ROOMID = new javax.swing.JTextField();
        INSERT = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        GENDER = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table5 = new javax.swing.JTable();
        DELETE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        READ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                  STUDENT   INFORMATION");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STUDENT USN:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, -1));

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FATHER NAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, -1));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DEPARTMENT:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, -1));

        jLabel7.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADDRESS:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, -1));

        jLabel8.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));

        jLabel9.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AGE:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, -1));

        DOB.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("DOB:");
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, -1));

        jLabel11.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HOSTEL ID:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, -1));

        jLabel12.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ROOM ID:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 90, 30));

        USN.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(USN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, -1));

        NAME.setBackground(new java.awt.Color(240, 240, 240));
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 90, -1));

        FNAME.setBackground(new java.awt.Color(240, 240, 240));
        FNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 90, -1));

        DEPT.setBackground(new java.awt.Color(240, 240, 240));
        DEPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPTActionPerformed(evt);
            }
        });
        getContentPane().add(DEPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 90, -1));

        ADD.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, -1));

        PHN.setBackground(new java.awt.Color(240, 240, 240));
        PHN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHNActionPerformed(evt);
            }
        });
        getContentPane().add(PHN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 90, -1));

        AGE.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, -1));

        HOSTELID.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(HOSTELID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 90, -1));

        ROOMID.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(ROOMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 90, -1));

        INSERT.setBackground(new java.awt.Color(34, 167, 240));
        INSERT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        INSERT.setText("INSERT");
        INSERT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        getContentPane().add(INSERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 90, -1));

        jLabel13.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("GENDER:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, -1));

        GENDER.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 90, -1));

        table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " USN", "NAME", "F NAME", "DEPT", "ADDRESS", "PHONE", "GENDER", "AGE", "DOB", "HOSTEL ID", "ROOM ID"
            }
        ));
        table5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table5MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 680, 250));

        DELETE.setBackground(new java.awt.Color(34, 167, 240));
        DELETE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DELETE.setText("DELETE");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 450, 90, -1));

        UPDATE.setBackground(new java.awt.Color(34, 167, 240));
        UPDATE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UPDATE.setText("UPDATE");
        UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 450, 90, -1));

        READ.setBackground(new java.awt.Color(34, 167, 240));
        READ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        READ.setText("READ");
        READ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        READ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                READActionPerformed(evt);
            }
        });
        getContentPane().add(READ, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 90, -1));

        jButton1.setBackground(new java.awt.Color(34, 167, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 510, -1, -1));

        jButton2.setBackground(new java.awt.Color(34, 167, 240));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hm/IMG-20181107-WA0019.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void FNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNAMEActionPerformed

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        Connection con;
        Statement st;
        ResultSet rst;
        
        Date date = null;
        
        String CONN_STRING;
        String USERNAME;
        String PASSWORD;
        String Password_Field = null;
        String Password_Input = null;
        String Studentusn= null;
        int Phone=0, Age=0,Hostelid=0, Roomid=0;
        
        String Name=null, Fathername=null, Department=null, Gender=null,Address=null;
        String query;
        Studentusn = this.USN.getText();
        Name = this.NAME.getText();
        Fathername = this.FNAME.getText();
        Department = this.DEPT.getText();
        Gender= this.GENDER.getText();
        Address = this.ADD.getText();
        Phone= Integer.parseInt(this.PHN.getText());
        Age = Integer.parseInt(this.AGE.getText());
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String Date=sdf.format(JTextField.getDate());
        Hostelid= Integer.parseInt(this.HOSTELID.getText());
        Roomid = Integer.parseInt(this.ROOMID.getText());
      
      
        
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USERNAME = "root";
        PASSWORD = "";
        query = "insert into student(STUDENT_USN,STUDENT_NAME,STUDENT_FATHER_NAME,DEPARTMENT,GENDER,ADDRESS,PHONE_NO,STUDENT_AGE,STUDENT_DOB,HOSTEL_ID,ROOM_ID) values ('"+Studentusn+"','"+Name+"','"+Fathername+"','"+Department+"','"+Gender+"','"+Address+"','"+Phone+"','"+Age+"','"+Date+"','"+Hostelid+"','"+Roomid+"')";
        try {
            
            con = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            st = con.createStatement();
            st.executeUpdate(query);
            DefaultTableModel model = (DefaultTableModel) table5.getModel();
            model.addRow(new Object[]{Studentusn,Name,Fathername,Department,Gender,Address,Phone,Age,Date,Hostelid,Roomid});
          JOptionPane.showMessageDialog(rootPane, "Inserted Successful");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR IN THE CODE..." + e);
            System.out.println(e);
        }

        
        
    
    }//GEN-LAST:event_INSERTActionPerformed

    private void PHNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PHNActionPerformed

    private void DEPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEPTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String action = evt.getActionCommand();
        if(action.equals("CANCEL")){
                 Option nm=new Option();
            nm.setVisible(true);
            dispose();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void READActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_READActionPerformed
                Connection con;
        Statement st;
        ResultSet rst;
        
        String CONN_STRING;
        String USERNAME;
        String PASSWORD;
        String Password_Field = null;
        String Password_Input = null;
        String Studentusn1= null;
        String Phone1=null, Age1=null,Hostelid1=null, Roomid1=null;
        
        String Name1=null, Fathername1=null, Department1=null, Gender1=null,Address1=null,Date1=null;
        String query;
   
        
        
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USERNAME = "root";
        PASSWORD = "";
        query = "CALL Student()";
        try {
            
            con = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            st = con.createStatement();
            rst = st.executeQuery(query);
            while (rst.next()) {                
                Studentusn1 = rst.getString("STUDENT_USN");
               Name1= rst.getString("STUDENT_NAME");
                Fathername1= rst.getString("STUDENT_FATHER_NAME");
               Department1 = rst.getString("DEPARTMENT");
               Gender1 = rst.getString("GENDER");
                 Address1 = rst.getString("ADDRESS");
                   Phone1 = rst.getString("PHONE_NO");
                     Age1 = rst.getString("STUDENT_AGE");
                    Date1 = rst.getString("STUDENT_DOB");
                    Hostelid1 = rst.getString("HOSTEL_ID");
                    Roomid1 = rst.getString("ROOM_ID");
               DefaultTableModel model = (DefaultTableModel) table5.getModel();
                model.addRow(new Object[]{Studentusn1,Name1,Fathername1,Department1,Gender1,Address1,Phone1,Age1,Date1,Hostelid1,Roomid1});
            }
            JOptionPane.showMessageDialog(rootPane, "Successful");
            
       

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR IN THE CODE..." + e);
            System.out.println(e);
        }
    }//GEN-LAST:event_READActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
      
        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
        String query_1 = "select * from student";
        String STUDENT_USN = null, query,student_usn = this.USN.getText(),set = "false";
        String name= null,fathername = null, department = null, address=null,phone=null,gender=null,age=null,dob=null,hostel_id=null,room_id=null;
        try {
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();
                
                query = "delete from student where STUDENT_USN = '"+student_usn+"'";
                st.executeUpdate(query);
                set = "true";
                DefaultTableModel model = (DefaultTableModel) table5.getModel();
                model.setRowCount(0);

                while(true){
                       rst = st.executeQuery("select * from student");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   student_usn = rst.getString("STUDENT_USN");
                                   name = rst.getString("STUDENT_NAME");
                                   fathername = rst.getString("STUDENT_FATHER_NAME");
                                   department = rst.getString("DEPARTMENT");
                                   gender = rst.getString("HOSTEL_ID");
                                   address = rst.getString("ADDRESS");
                                   phone = rst.getString("PHONE_NO");
                                   age = rst.getString("STUDENT_AGE");
                                   dob = rst.getString("STUDENT_DOB");
                                   hostel_id = rst.getString("HOSTEL_ID");
                                   room_id = rst.getString("ROOM_ID");
                                   DefaultTableModel model1 = (DefaultTableModel) this.table5.getModel();
                                   model1.addRow(new Object[] {student_usn,name,fathername,department,gender,address,phone,age,dob,hostel_id,room_id});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
             JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }

    }//GEN-LAST:event_DELETEActionPerformed

    private void table5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table5MouseClicked
         
        try{
            DefaultTableModel model1= (DefaultTableModel)table5.getModel();
            int index=table5.getSelectedRow();
            java.util.Date date =new SimpleDateFormat("yyyy-MM-dd").parse((String)model1.getValueAt(index, 8));
        JTextField.setDate(date);
        }catch(ParseException ex){
      
        }
        int i=table5.getSelectedRow();
        TableModel model= table5.getModel();
        USN.setText(model.getValueAt(i,0).toString());
        NAME.setText(model.getValueAt(i, 1).toString());
        FNAME.setText(model.getValueAt(i, 2).toString());
        DEPT.setText(model.getValueAt(i, 3).toString());
        ADD.setText(model.getValueAt(i, 4).toString());
        PHN.setText(model.getValueAt(i, 5).toString());
        GENDER.setText(model.getValueAt(i, 6).toString());
        AGE.setText(model.getValueAt(i, 7).toString());
        HOSTELID.setText(model.getValueAt(i, 9).toString());
        ROOMID.setText(model.getValueAt(i, 10).toString());
       
    }//GEN-LAST:event_table5MouseClicked

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
       Connection con;
       Statement st;
       ResultSet rst;
       
       String CONN_STRING;
       String USER_NAME;
       String PASSWORD;
        String Studentusn=null, Phone=null, Age=null,Hostelid=null, Roomid=null;
        String Name=null, Fathername=null, Department=null, Gender=null,Address=null,Date=null;       

        CONN_STRING = "jdbc:mysql://localhost:3306/hostel";
        USER_NAME = "root";
        PASSWORD = "";
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(JTextField.getDate());
       
        Studentusn= this.USN.getText();
        Name = this.NAME.getText();
        Fathername = this.FNAME.getText();
        Department= this.DEPT.getText();
        Gender= this.ADD.getText();
        Address= this.PHN.getText();
        Phone= this.GENDER.getText();
        Age= this.AGE.getText();
        Hostelid= this.HOSTELID.getText();
        Roomid= this.ROOMID.getText();
        String studentusn= null;
        String query_1 = "select * from student";
        String name = null,fname = null, dept = null,gen=null,address=null,phn=null,age=null,dob=null,hst=null,room=null;
        

        try {
            
            String query = null,querry_2 = null;
            con = DriverManager.getConnection(CONN_STRING,USER_NAME,PASSWORD);
            st = con.createStatement();

            String set = "false";

             

                query = "update student set STUDENT_USN = '"+Studentusn+"',"
                + "STUDENT_NAME = '"+Name+"',STUDENT_FATHER_NAME = '"+Fathername+"',"
                + "DEPARTMENT = '"+Department+"',GENDER = '"+Gender+"',ADDRESS = '"+Address+"',PHONE_NO = '"+Phone+"',STUDENT_AGE = '"+Age+"',STUDENT_DOB = '"+date+"',HOSTEL_ID = '"+Hostelid+"',ROOM_ID = '"+Roomid+"' where STUDENT_USN = '"+Studentusn+"'";
                st.executeUpdate(query);
                DefaultTableModel model = (DefaultTableModel) table5.getModel();
                set = "true";
                model.setRowCount(0);

                while(true){
                       rst = st.executeQuery("select * from student");
                       if (set.equals("true")) {
                           while(rst.next()) {                    
                                   Studentusn = rst.getString("STUDENT_USN");
                                   name = rst.getString("STUDENT_NAME");
                                   fname = rst.getString("STUDENT_FATHER_NAME");
                                   dept = rst.getString("DEPARTMENT");
                                   gen = rst.getString("GENDER");
                                   address = rst.getString("ADDRESS");
                                   phn = rst.getString("PHONE_NO");
                                   age = rst.getString("STUDENT_AGE");
                                   dob = rst.getString("STUDENT_DOB");
                                   hst = rst.getString("HOSTEL_ID");
                                   room = rst.getString("ROOM_ID");
                                   DefaultTableModel model1 = (DefaultTableModel) this.table5.getModel();
                                   model1.addRow(new Object[] {Studentusn,name,fname,dept,gen,address,phn,age,dob,hst,room});
                           } 
                       }else {
                           JOptionPane.showMessageDialog(rootPane, "nothing to update");
                       }
                       break;
                   }
            JOptionPane.showMessageDialog(rootPane,"successfully updated!!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
            System.out.println(e);
        }

    }//GEN-LAST:event_UPDATEActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Mess hg= new Mess();
       hg.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADD;
    private javax.swing.JTextField AGE;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField DEPT;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField FNAME;
    private javax.swing.JTextField GENDER;
    private javax.swing.JTextField HOSTELID;
    private javax.swing.JButton INSERT;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PHN;
    private javax.swing.JButton READ;
    private javax.swing.JTextField ROOMID;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField USN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table5;
    // End of variables declaration//GEN-END:variables
}
